n_completo = str(input('Digite seu nome completo: ')).strip()
nome = n_completo.split()
print('Muito prazer em te conhecer!' )
print('Seu primeiro nome é: {}'.format(nome[0]))
print('Seu penultimo nome é: {}'.format(nome[len(nome)-2]))
print('Seu ultimo nome é: {}'.format(nome[len(nome)-1]))
